### ISSUE TITLE
Tweaks to status board UX

### ISSUE THREAD

**Issue by nikolajbaer** [codeforamerica/brigade-project-index-statusboard#1]
- [ ] change title of brigades to "By Brigade" rather than leaders
- [ ] change title of topics "Github Topic Tags By Use"
- [ ] Show check for github description, and project count
- [ ] Add legend to a map
- [ ] make black dot bigger and gray
- [ ] add zoom to map

**Comment by mmazanec22** [comment]
Closing this since we're pretty far along on the react reset branch.
