### ISSUE TITLE
Display the correct number of projects shown on `/projects`

### ISSUE THREAD

**Issue by k3KAW8Pnf7mkmdSMPHz27** [codeforamerica/brigade-project-index-statusboard#102]
# Describe the bug

The `Showing 4 projects...` does not match the number of projects displayed when the tables filter is used. In the screenshot, it claims 4 projects are shown, while in reality there is only one because the `Project` is filtered to projects containing `data`.

<img width="752" alt="Skärmavbild 2021-08-05 kl  15 06 09" src="https://user-images.githubusercontent.com/2598631/128406933-2a98043a-67be-4ef7-9100-8beb904e854c.png">

# To Reproduce

1. Go to https://projects.brigade.network/projects?timeRange=all+time&topics=courtbot&name=data (filter topics to "courtbot" and projects to "data")
2. See that the number of projects displayed doesn't match the numbers claimed to be shown

# Expected behavior

The number of displayed projects should match the claimed number of displayed projects

# Additional context

One potential strategy could be to,
1. create a counter using `useState` in https://github.com/codeforamerica/brigade-project-index-statusboard/blob/main/statusboard/src/pages/Projects/Projects.tsx
2. use the `setCounter` from step 1 as an optional parameter to https://github.com/codeforamerica/brigade-project-index-statusboard/blob/main/statusboard/src/components/ProjectsTable/ProjectsTable.tsx
3. use the length of https://github.com/codeforamerica/brigade-project-index-statusboard/blob/88a843ea373ebc30fc2aedfbb44288496c2c199f/statusboard/src/components/ProjectsTable/ProjectsTable.tsx#L24 to update the `setCounter`
4. use the `counter` created in step 1 to display the number of rows in https://github.com/codeforamerica/brigade-project-index-statusboard/blob/88a843ea373ebc30fc2aedfbb44288496c2c199f/statusboard/src/pages/Projects/Projects.tsx#L96

**Comment by rajkumawat01** [comment]
Is this issue been solved?

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Hello @rajkumawat01, it is in being solved by @rkaufman13 in #129
