### ISSUE TITLE
Code for America projects aren't shown on `/projects`

### ISSUE THREAD

**Issue by k3KAW8Pnf7mkmdSMPHz27** [codeforamerica/brigade-project-index-statusboard#103]
# Is your feature request related to a problem? Please describe. 

Only brigades are listed on the `/projects` page. It would be a good idea to at least list Code for America projects as well.

**Comment by giosce** [comment]
Once someone approve/merge https://github.com/codeforamerica/brigade-information/pull/136 data should be collected by the crawler and displayed in the UI.
