### ISSUE TITLE
Add Puerto Rico and other US Territories to Map

### ISSUE THREAD

**Issue by nikolajbaer** [codeforamerica/brigade-project-index-statusboard#12]
The out-of-box US Albers projection used for the map does not include US Territories like Puerto Rico. 

We should ideally have them included on the map, or at the very least have them listed under the map .

**Comment by nihonjinrxs** [comment]
Here's an example I found of a function that adds Puerto Rico: https://bl.ocks.org/HarryStevens/0e440b73fbd88df7c6538417481c9065

Could likely be adapted.

**Comment by nikolajbaer** [comment]
Thanks @nihonjinrxs 

I followed the breadcrumbs and found:
https://www.npmjs.com/package/d3-composite-projections

Which packages this all up with Guam and other territories as well. 

I am working on getting this integrated with the map.

**Comment by nikolajbaer** [comment]
This is now deployed on the live site.
