### ISSUE TITLE
Use New Relic for analytics

### ISSUE THREAD

**Issue by mmazanec22** [codeforamerica/brigade-project-index-statusboard#132]
**Is your feature request related to a problem? Please describe.**
Per @k3KAW8Pnf7mkmdSMPHz27's request, let's set up New Relic for analytics.

**Describe the solution you'd like**
Seems like accounts exist on a per brigade basis and that this project needs to be adopted by a brigade. Maybe @themightychris can adopt the Statusboard on behalf of Code for Philly?

**Describe alternatives you've considered**
We could use Google Analytics or something, but this kind of begs the same questions about what account to use. Potentially we could set up a Google Group to be the account manager?

**Additional context**
In the long term, post brigade revisioning, CfA might need to re-think how we set up accounts. IMO we can cross that bridge when we come to it.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@themightychris can set up NewRelic through Code for Philly. The missing part right now is someone having time to do it and figure out all the necessary details. (it is on my todo list, but I am not sure when I'll have time)

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I am closing this. We can open a new issue to make the information we collect more transparent in the future.
