### ISSUE TITLE
Add More Columns

### ISSUE THREAD

**Issue by giosce** [codeforamerica/brigade-project-index-statusboard#137]
Add the last_commit column
Perhaps more columns (like number of open issues, num of contributors).
All these columns should be sortable.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
On a side-note. We can also sort on hidden columns. If there is some kind of sorting behavior we'd like to have, but we don't want to display the data (or display it in a different way) it is possible with `react-table`.

**Comment by giosce** [comment]
In back-end index toml files we have link_url = "https://covidcalc.org" (webpage of the running project) and we are adding open_issues_within (by buckets, we'll adjust the intervals).

**Comment by giosce** [comment]
Added number of issues and last_commit. Closing this, we can discuss what else and how to add more info.
