### ISSUE TITLE
Visual Design Updates

### ISSUE THREAD

**Issue by nikolajbaer** [codeforamerica/brigade-project-index-statusboard#2]
- [ ] Change Link / Header color to Blue, not Red
- [ ] make brigade topic listing green for the checkmark to be consistent
- [ ] use pagespeed iconography - red triangle, yellow square, green dot (see google pagespeed insights for example)

**Comment by mmazanec22** [comment]
What will pagespeed iconography be used for?

**Comment by nikolajbaer** [comment]
The idea is to help prioritize project owners on improving their meta data.

E.g. adding a README and topic tags might be a red triangle - get this done, like adding a title tag to your webpage

adding a publiccode.yml maybe a yellow square - should do this, like adding schema.org tag to a web page

confirming you have a description - something that is good to go

**Comment by mmazanec22** [comment]
Closing this since we're pretty far along on the react reset branch.  I have a feeling these features are still relevant, so we should prob discuss at some point and open a new ticket about how we want to implement the "documentation peer pressure" part of this project!
