### ISSUE TITLE
Reset scroll on router change

### ISSUE THREAD

**Issue by mmazanec22** [codeforamerica/brigade-project-index-statusboard#21]
Right now, when you click something that is farther down the page, it loads the new page in a scrolled-down position.  The scroll should be reset to the top, unless we're intentionally navigating to a certain section.

**Comment by nikolajbaer** [comment]
This is now updated on the dev site:

https://brigade-project-index-dev.herokuapp.com/

It will go out when i push through the next pull request

**Comment by nikolajbaer** [comment]
This is updated on live site.
