### ISSUE TITLE
React icon shows up in slack preview instead of our favicon

### ISSUE THREAD

**Issue by mmazanec22** [codeforamerica/brigade-project-index-statusboard#48]
It's like, a tiny tiny issue but kind of annoying.  We should use our beautiful favicon instead!

**Comment by giosce** [comment]
When sending the URL in Slack it also shows the name of the app as "Web site created using create-react-app".
It would be great to change it to "CfA Brigade Network Index" or something similar.
Unfortunately I don't know how to make the change, sorry.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
This is fixed by #73?

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Fixed by @WesleySalesberry in #73.
