### ISSUE TITLE
Change old main branch name to "old vue version" or something like that

### ISSUE THREAD

**Issue by mmazanec22** [codeforamerica/brigade-project-index-statusboard#50]
We shouldn't use master anymore, and also react-reset is basically the base branch now.  I'd vote for "base" as our base branch, but am open to something else if anyone has strong feelings.  Open q: will anything break if we change the base branch?

**Comment by tdooner** [comment]
I think `main` seems to be the standard the community is trending towards, so I would advocate for that.

I bet that things will break but let's give it a try anyway. For Heroku they still require deploys to go to the `master` branch.

**Comment by mmazanec22** [comment]
Changed the main branch to `main` with the latest changes from react-reset.  I think it's safe to delete both master and react-reset as soon as we figure out what we broke/might break with this change :sweat_smile:

**Comment by mmazanec22** [comment]
We're using main as our branch name and I have removed the old branches
