### ISSUE TITLE
Add Typescript

### ISSUE THREAD

**Issue by tdooner** [codeforamerica/brigade-project-index-statusboard#53]

**Comment by mmazanec22** [comment]
We should probably do this before we write any more code

**Comment by tdooner** [comment]
Wasted 2 hours on this trying various versions of everything, deleting node_modules directory, all the annoying JS bullshit I hate so much.

Finally ended up with this:
![image](https://user-images.githubusercontent.com/129120/99869753-5105a780-2b82-11eb-942d-a5fe724d82ac.png)

A totally inscrutable error message.  I copied our `src` directory into a brand new CRA generated from scratch, and got the same error. I'm giving up for now.

**Comment by tdooner** [comment]
But if you want to try, please do!
