### ISSUE TITLE
Analytics of some kind

### ISSUE THREAD

**Issue by mmazanec22** [codeforamerica/brigade-project-index-statusboard#61]
Not necessarily google; maybe a creative use of application logs

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
If someone else is looking at this topic, #6 has a discussion on the pros/cons of Google Analytics.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
It might be possible to get [New Relic access through CfA](https://brigade.codeforamerica.org/resources/software/newrelic/). I am assuming the page refers to last November.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I am closing this for now, since we have some rudimentary New Relic tracking
