### ISSUE TITLE
Add a Taxonomy page

### ISSUE THREAD

**Issue by giosce** [codeforamerica/brigade-project-index-statusboard#81]
While we keep working on the taxonomy (list and categorization of topics) it would be great to use the current api https://statusboard.brigade.cloud/api/taxonomy.json (or discuss if api needs to be different) to get the data to build an additional page (along side "Map" and "About").
First version of this page perhaps just being a three of folders and topics within, expandable folders, possibly with a search feature.

**Comment by giosce** [comment]
For Congress 2021 we'll just have a link to https://codeforamerica.github.io/civic-tech-taxonomy/editor-ui/

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@giosce why not include the page? What is the remaining issue with using the current API (is it only `axios`, because it is already included in the Statusboard)?
