### ISSUE TITLE
Range dropdown not visible on phone

### ISSUE THREAD

**Issue by giosce** [codeforamerica/brigade-project-index-statusboard#88]
On an iphone, the dropdown to select the "modify within the last <period>" is not visible, not even trying to scroll the page horizontally.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@giosce the `changes on GitHub in the last...` ?
If that is the case, could you try the preview in https://github.com/codeforamerica/brigade-project-index-statusboard/pull/78 ?
https://deploy-preview-78--dreamy-snyder-8339ae.netlify.app/?timeRange=year

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Fixed in #78.
