### ISSUE TITLE
Allow filtering / viewing of projects that have multiple topic tags

### ISSUE THREAD

**Issue by nikolajbaer** [codeforamerica/brigade-project-index-statusboard#9]
Add a way for users to look at projects that match multiple topic tags.

The simplest place to add this in the UI might be at the top of the topic detail listing with a call like "Add Topic Filter". The UI might also need to change to have a list of all "topics" at the top with little "X"s to clear them from the filter, as well as an input box that does a suggested/filtering list as you type in the topic tag.

**Comment by nikolajbaer** [comment]
The first version of this is now available on the dev site.

Still needed would be a suggestion box as the user types .

**Comment by mmazanec22** [comment]
Implemented in #40
