### ISSUE TITLE
Extra `Loading...` text in the table when no projects are matched

### ISSUE THREAD

**Issue by k3KAW8Pnf7mkmdSMPHz27** [codeforamerica/brigade-project-index-statusboard#94]
### Describe the bug

There is `Loading...` text when nothing is loading in the table.

### To Reproduce

1. https://projects.brigade.network/
2. Type in a filter that doesn't match any projects
3. There is `Loading...` text despite nothing loading

### Expected behavior

There should only be a `Loading...` text when something is actually loading.

### Screenshots

<img width="612" alt="Skärmavbild 2021-07-21 kl  17 01 07" src="https://user-images.githubusercontent.com/2598631/126559806-7bfda163-9420-4c4c-ba33-bfe44ff2448c.png">

**Additional context**

This is likely a good starting point

https://github.com/codeforamerica/brigade-project-index-statusboard/blob/a7069c8122f5feb98e9dac336dfdfc969c5e3118/statusboard/src/components/ProjectsTable/ProjectsTable.tsx#L48-L54

There might be a good unit test to add here.

**Comment by DenysLins** [comment]
Hi @k3KAW8Pnf7mkmdSMPHz27 Can I work on that?

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@DenysLins sure, go ahead!

I am trying to re-build the infrastructure a bit so be aware that,

* There are some suggested changes in the getting started section https://github.com/k3KAW8Pnf7mkmdSMPHz27/brigade-project-index-statusboard/blob/update-statusboard-instructions/README.md
* The ESLinter isn't working that well (yet) https://github.com/codeforamerica/brigade-project-index-statusboard/pull/83
* There is a failing unit test https://github.com/codeforamerica/brigade-project-index-statusboard/pull/91

Feel free to chime in with any comments in those PRs as well!

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@DenysLins just checking if you experienced any issues getting things up and running? I am looking to improve the developer experience and documentation wherever it is possible.
